# Generated by Django 4.0.4 on 2022-06-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
